# Generated by Django 3.2.6 on 2021-09-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('department', models.CharField(blank=True, max_length=30, verbose_name='Department')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Position')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('item_number', models.CharField(max_length=5, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('configuration', models.URLField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('employee_start_date', models.DateField(blank=True, null=True)),
                ('in_use_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipped', to='employees.employee')),
                ('paid_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paid', to='employees.employee')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
    ]
